### ISSUE TITLE
distinction between adapter and client?

### ISSUE THREAD

**Issue by dbu** [php-http/httplug.github.io#1]
i am not sure we need to distinguish between client and adapter there. for the end user, its not that important. and i am not sure if we want to explicitly list them on the page (meaning we need to maintain that list) or should just explain the concept and link to packagist. also relates to https://github.com/php-http/documentation/issues/23 - maybe we should provide the general background information on virtual packages here on the website instead of in the doc? or link to the doc from the web site?

**Comment by sagikazarmark** [comment]
Agree, just wanted to play with the data feature of Jekyll :stuck_out_tongue_winking_eye:

**Comment by dbu** [comment]
so do you mind if i remove all that and replace it with links to
packagist on the main page?

**Comment by sagikazarmark** [comment]
Not at all. Probably it could link to the client-implementation search on packagist. We could merge them under Clients.

**Comment by sagikazarmark** [comment]
Is this resolved?

**Comment by dbu** [comment]
yep. 

btw looking at the clients list on packagist i discovered https://github.com/jack-theripper/curl-client which seems to be a fork of the curl client. we should check if we can motivate the author to do pull requests to improve the php-http curl client instead of maintaining a fork...

**Comment by sagikazarmark** [comment]
I think this guy is the once submitted some changes, those were not so good: https://github.com/php-http/curl-client/pull/19

**Comment by dbu** [comment]
oh well, right.
