### ISSUE TITLE
Update media with Davids talk

### ISSUE THREAD

**Issue by Nyholm** [php-http/httplug.github.io#13]

**Comment by sagikazarmark** [comment]
Which one exactly?

**Comment by Nyholm** [comment]
Not sure to be honest. I just remember seeing a tweet last week that he was doing a talk at a larger conference.

**Comment by dbu** [comment]
i did not do a talk on httplug recently. i tweeted about the article in php architect, but as that is a payed magazine i don't think we should list that in media. at confoo i talked about other topics (symfony and varnish)

**Comment by Nyholm** [comment]
Oh, that right. My bad.
